services:
  backend:
    volumes:
      - ./database.db:/app/database.db
    build:
      context: ./backend
    env_file:
      - .env

  agent:
    build:
      context: ./agent
    env_file:
      - .env
    depends_on:
      - backend

  caddy:
    image: caddy
    volumes:
      - ./frontend:/var/www/frontend:ro
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
    ports:
      - "80:80"
    depends_on:
      - backend